// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: api/codesurgeon.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for GetOpenAPI
type GetOpenAPIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOpenAPIRequest) Reset() {
	*x = GetOpenAPIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenAPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenAPIRequest) ProtoMessage() {}

func (x *GetOpenAPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenAPIRequest.ProtoReflect.Descriptor instead.
func (*GetOpenAPIRequest) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{0}
}

// Response message for GetOpenAPI
type GetOpenAPIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openapi string `protobuf:"bytes,1,opt,name=openapi,proto3" json:"openapi,omitempty"`
}

func (x *GetOpenAPIResponse) Reset() {
	*x = GetOpenAPIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenAPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenAPIResponse) ProtoMessage() {}

func (x *GetOpenAPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenAPIResponse.ProtoReflect.Descriptor instead.
func (*GetOpenAPIResponse) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{1}
}

func (x *GetOpenAPIResponse) GetOpenapi() string {
	if x != nil {
		return x.Openapi
	}
	return ""
}

// Request message for Introductiono
type IntroductionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short bool `protobuf:"varint,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *IntroductionRequest) Reset() {
	*x = IntroductionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntroductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionRequest) ProtoMessage() {}

func (x *IntroductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionRequest.ProtoReflect.Descriptor instead.
func (*IntroductionRequest) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{2}
}

func (x *IntroductionRequest) GetShort() bool {
	if x != nil {
		return x.Short
	}
	return false
}

// Response message for Introduction
type IntroductionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Introduction string `protobuf:"bytes,1,opt,name=introduction,proto3" json:"introduction,omitempty"`
}

func (x *IntroductionResponse) Reset() {
	*x = IntroductionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntroductionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionResponse) ProtoMessage() {}

func (x *IntroductionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionResponse.ProtoReflect.Descriptor instead.
func (*IntroductionResponse) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{3}
}

func (x *IntroductionResponse) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

type SearchForFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// path is the path to the file or directory to search for the function
	Path         string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FunctionName string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// receiver is optional, only used if search for a method in a struct
	Receiver string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *SearchForFunctionRequest) Reset() {
	*x = SearchForFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFunctionRequest) ProtoMessage() {}

func (x *SearchForFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFunctionRequest.ProtoReflect.Descriptor instead.
func (*SearchForFunctionRequest) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{4}
}

func (x *SearchForFunctionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchForFunctionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *SearchForFunctionRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type SearchForFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filepath      string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	FunctionName  string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Documentation string `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	// receiver is optional, only used if search for a method in a struct
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Body     string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SearchForFunctionResponse) Reset() {
	*x = SearchForFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFunctionResponse) ProtoMessage() {}

func (x *SearchForFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFunctionResponse.ProtoReflect.Descriptor instead.
func (*SearchForFunctionResponse) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{5}
}

func (x *SearchForFunctionResponse) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *SearchForFunctionResponse) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *SearchForFunctionResponse) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *SearchForFunctionResponse) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SearchForFunctionResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UpsertDocumentationToFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// filepath is the path to the file where the function is located
	Filepath      string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	FunctionName  string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Documentation string `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	// receiver is optional, only used if search for a method in a struct
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *UpsertDocumentationToFunctionRequest) Reset() {
	*x = UpsertDocumentationToFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertDocumentationToFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDocumentationToFunctionRequest) ProtoMessage() {}

func (x *UpsertDocumentationToFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDocumentationToFunctionRequest.ProtoReflect.Descriptor instead.
func (*UpsertDocumentationToFunctionRequest) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertDocumentationToFunctionRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *UpsertDocumentationToFunctionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *UpsertDocumentationToFunctionRequest) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *UpsertDocumentationToFunctionRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type UpsertDocumentationToFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UpsertDocumentationToFunctionResponse) Reset() {
	*x = UpsertDocumentationToFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertDocumentationToFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDocumentationToFunctionResponse) ProtoMessage() {}

func (x *UpsertDocumentationToFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDocumentationToFunctionResponse.ProtoReflect.Descriptor instead.
func (*UpsertDocumentationToFunctionResponse) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertDocumentationToFunctionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UpsertCodeBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modification *UpsertCodeBlockRequest_Modification `protobuf:"bytes,1,opt,name=modification,proto3" json:"modification,omitempty"`
}

func (x *UpsertCodeBlockRequest) Reset() {
	*x = UpsertCodeBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCodeBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCodeBlockRequest) ProtoMessage() {}

func (x *UpsertCodeBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCodeBlockRequest.ProtoReflect.Descriptor instead.
func (*UpsertCodeBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertCodeBlockRequest) GetModification() *UpsertCodeBlockRequest_Modification {
	if x != nil {
		return x.Modification
	}
	return nil
}

type UpsertCodeBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UpsertCodeBlockResponse) Reset() {
	*x = UpsertCodeBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCodeBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCodeBlockResponse) ProtoMessage() {}

func (x *UpsertCodeBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCodeBlockResponse.ProtoReflect.Descriptor instead.
func (*UpsertCodeBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertCodeBlockResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Request message for ParseCodebase
type ParseCodebaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileOrDirectory string `protobuf:"bytes,1,opt,name=file_or_directory,json=fileOrDirectory,proto3" json:"file_or_directory,omitempty"` // The path to the file or directory to be parsed
}

func (x *ParseCodebaseRequest) Reset() {
	*x = ParseCodebaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseCodebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCodebaseRequest) ProtoMessage() {}

func (x *ParseCodebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCodebaseRequest.ProtoReflect.Descriptor instead.
func (*ParseCodebaseRequest) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{10}
}

func (x *ParseCodebaseRequest) GetFileOrDirectory() string {
	if x != nil {
		return x.FileOrDirectory
	}
	return ""
}

// Response message for ParseCodebase
type ParseCodebaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packages []*Package `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"` // List of parsed packages
}

func (x *ParseCodebaseResponse) Reset() {
	*x = ParseCodebaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseCodebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCodebaseResponse) ProtoMessage() {}

func (x *ParseCodebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCodebaseResponse.ProtoReflect.Descriptor instead.
func (*ParseCodebaseResponse) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{11}
}

func (x *ParseCodebaseResponse) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

// Representation of a parsed package
type Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package    string       `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Imports    []string     `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports,omitempty"`
	Structs    []*Struct    `protobuf:"bytes,3,rep,name=structs,proto3" json:"structs,omitempty"`
	Functions  []*Function  `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
	Variables  []*Variable  `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	Constants  []*Constant  `protobuf:"bytes,6,rep,name=constants,proto3" json:"constants,omitempty"`
	Interfaces []*Interface `protobuf:"bytes,7,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{12}
}

func (x *Package) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Package) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *Package) GetStructs() []*Struct {
	if x != nil {
		return x.Structs
	}
	return nil
}

func (x *Package) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Package) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Package) GetConstants() []*Constant {
	if x != nil {
		return x.Constants
	}
	return nil
}

func (x *Package) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// Representation of a parsed interface
type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Methods []*Method `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	Docs    []string  `protobuf:"bytes,3,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{13}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetMethods() []*Method {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Interface) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

// Representation of a parsed struct
type Struct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields  []*Field  `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Methods []*Method `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	Docs    []string  `protobuf:"bytes,4,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *Struct) Reset() {
	*x = Struct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{14}
}

func (x *Struct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Struct) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Struct) GetMethods() []*Method {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Struct) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

// Representation of a parsed method
type Method struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver  string   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // Receiver type (e.g., "*MyStruct" or "MyStruct")
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params    []*Param `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Returns   []*Param `protobuf:"bytes,4,rep,name=returns,proto3" json:"returns,omitempty"`
	Docs      []string `protobuf:"bytes,5,rep,name=docs,proto3" json:"docs,omitempty"`
	Signature string   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Body      string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"` // Body of the method
}

func (x *Method) Reset() {
	*x = Method{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method) ProtoMessage() {}

func (x *Method) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method.ProtoReflect.Descriptor instead.
func (*Method) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{15}
}

func (x *Method) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Method) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Method) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Method) GetReturns() []*Param {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Method) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *Method) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Method) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Representation of a parsed function
type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params    []*Param `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Returns   []*Param `protobuf:"bytes,3,rep,name=returns,proto3" json:"returns,omitempty"`
	Docs      []string `protobuf:"bytes,4,rep,name=docs,proto3" json:"docs,omitempty"`
	Signature string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Body      string   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"` // Body of the function
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{16}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Function) GetReturns() []*Param {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Function) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *Function) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Function) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Representation of a parameter for functions and methods
type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the parameter or return value
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Type (e.g., "int", "*string")
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{17}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Representation of a field in a struct
type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Tag     string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Private bool     `protobuf:"varint,4,opt,name=private,proto3" json:"private,omitempty"`
	Pointer bool     `protobuf:"varint,5,opt,name=pointer,proto3" json:"pointer,omitempty"`
	Slice   bool     `protobuf:"varint,6,opt,name=slice,proto3" json:"slice,omitempty"`
	Docs    []string `protobuf:"bytes,7,rep,name=docs,proto3" json:"docs,omitempty"`
	Comment string   `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{18}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Field) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Field) GetPointer() bool {
	if x != nil {
		return x.Pointer
	}
	return false
}

func (x *Field) GetSlice() bool {
	if x != nil {
		return x.Slice
	}
	return false
}

func (x *Field) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *Field) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Representation of a parsed variable
type Variable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Docs []string `protobuf:"bytes,3,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *Variable) Reset() {
	*x = Variable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{19}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Variable) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

// Representation of a parsed constant
type Constant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Docs  []string `protobuf:"bytes,3,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *Constant) Reset() {
	*x = Constant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Constant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constant) ProtoMessage() {}

func (x *Constant) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constant.ProtoReflect.Descriptor instead.
func (*Constant) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{20}
}

func (x *Constant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Constant) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Constant) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type UpsertCodeBlockRequest_Modification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// filepath is the path to the file where the code block will be upserted
	Filepath string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	// package_name is the package name of the file that is used to create the file if not exists
	PackageName string `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// code_block is the code block to be upserted
	CodeBlock string `protobuf:"bytes,3,opt,name=code_block,json=codeBlock,proto3" json:"code_block,omitempty"`
	// overwrite is a flag to indicate if the code block should be overwritten if it already exists
	Overwrite bool `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
}

func (x *UpsertCodeBlockRequest_Modification) Reset() {
	*x = UpsertCodeBlockRequest_Modification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_codesurgeon_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCodeBlockRequest_Modification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCodeBlockRequest_Modification) ProtoMessage() {}

func (x *UpsertCodeBlockRequest_Modification) ProtoReflect() protoreflect.Message {
	mi := &file_api_codesurgeon_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCodeBlockRequest_Modification.ProtoReflect.Descriptor instead.
func (*UpsertCodeBlockRequest_Modification) Descriptor() ([]byte, []int) {
	return file_api_codesurgeon_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpsertCodeBlockRequest_Modification) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *UpsertCodeBlockRequest_Modification) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *UpsertCodeBlockRequest_Modification) GetCodeBlock() string {
	if x != nil {
		return x.CodeBlock
	}
	return ""
}

func (x *UpsertCodeBlockRequest_Modification) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

var File_api_codesurgeon_proto protoreflect.FileDescriptor

var file_api_codesurgeon_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72,
	0x67, 0x65, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x22, 0x2b, 0x0a, 0x13, 0x49, 0x6e, 0x74,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x22, 0x3a, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x6f, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x22, 0xb2, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f,
	0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x23, 0x0a,
	0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xa9, 0x01, 0x0a, 0x24, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x6f, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x23, 0x0a,
	0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x25, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0xfb, 0x01,
	0x0a, 0x16, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x8a,
	0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x17, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x42, 0x0a, 0x14, 0x50, 0x61, 0x72, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x4f,
	0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x49, 0x0a, 0x15, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67,
	0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x73, 0x22, 0xc3, 0x02, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72,
	0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75,
	0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x33,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75,
	0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52,
	0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x09, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x07,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x6f, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22,
	0x8b, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0xd8, 0x01,
	0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73,
	0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67,
	0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72,
	0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x2f, 0x0a, 0x05, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb9, 0x01, 0x0a, 0x05, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f,
	0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x48,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x32, 0xd3, 0x04, 0x0a, 0x0a, 0x47, 0x70, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x41, 0x50, 0x49, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67,
	0x65, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67,
	0x65, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72,
	0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73,
	0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x50,
	0x61, 0x72, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x62, 0x61, 0x73, 0x65, 0x12, 0x21, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73,
	0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x1d, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5c, 0x0a, 0x0f, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f,
	0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73,
	0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x95,
	0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65,
	0x6f, 0x6e, 0x42, 0x10, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x77, 0x72, 0x69, 0x63, 0x61, 0x72, 0x64, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65,
	0x2d, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0xa2, 0x02, 0x03, 0x43,
	0x58, 0x58, 0xaa, 0x02, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e,
	0xca, 0x02, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0xe2, 0x02,
	0x17, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x75, 0x72, 0x67, 0x65, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_codesurgeon_proto_rawDescOnce sync.Once
	file_api_codesurgeon_proto_rawDescData = file_api_codesurgeon_proto_rawDesc
)

func file_api_codesurgeon_proto_rawDescGZIP() []byte {
	file_api_codesurgeon_proto_rawDescOnce.Do(func() {
		file_api_codesurgeon_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_codesurgeon_proto_rawDescData)
	})
	return file_api_codesurgeon_proto_rawDescData
}

var file_api_codesurgeon_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_codesurgeon_proto_goTypes = []any{
	(*GetOpenAPIRequest)(nil),                     // 0: codesurgeon.GetOpenAPIRequest
	(*GetOpenAPIResponse)(nil),                    // 1: codesurgeon.GetOpenAPIResponse
	(*IntroductionRequest)(nil),                   // 2: codesurgeon.IntroductionRequest
	(*IntroductionResponse)(nil),                  // 3: codesurgeon.IntroductionResponse
	(*SearchForFunctionRequest)(nil),              // 4: codesurgeon.SearchForFunctionRequest
	(*SearchForFunctionResponse)(nil),             // 5: codesurgeon.SearchForFunctionResponse
	(*UpsertDocumentationToFunctionRequest)(nil),  // 6: codesurgeon.UpsertDocumentationToFunctionRequest
	(*UpsertDocumentationToFunctionResponse)(nil), // 7: codesurgeon.UpsertDocumentationToFunctionResponse
	(*UpsertCodeBlockRequest)(nil),                // 8: codesurgeon.UpsertCodeBlockRequest
	(*UpsertCodeBlockResponse)(nil),               // 9: codesurgeon.UpsertCodeBlockResponse
	(*ParseCodebaseRequest)(nil),                  // 10: codesurgeon.ParseCodebaseRequest
	(*ParseCodebaseResponse)(nil),                 // 11: codesurgeon.ParseCodebaseResponse
	(*Package)(nil),                               // 12: codesurgeon.Package
	(*Interface)(nil),                             // 13: codesurgeon.Interface
	(*Struct)(nil),                                // 14: codesurgeon.Struct
	(*Method)(nil),                                // 15: codesurgeon.Method
	(*Function)(nil),                              // 16: codesurgeon.Function
	(*Param)(nil),                                 // 17: codesurgeon.Param
	(*Field)(nil),                                 // 18: codesurgeon.Field
	(*Variable)(nil),                              // 19: codesurgeon.Variable
	(*Constant)(nil),                              // 20: codesurgeon.Constant
	(*UpsertCodeBlockRequest_Modification)(nil),   // 21: codesurgeon.UpsertCodeBlockRequest.Modification
}
var file_api_codesurgeon_proto_depIdxs = []int32{
	21, // 0: codesurgeon.UpsertCodeBlockRequest.modification:type_name -> codesurgeon.UpsertCodeBlockRequest.Modification
	12, // 1: codesurgeon.ParseCodebaseResponse.packages:type_name -> codesurgeon.Package
	14, // 2: codesurgeon.Package.structs:type_name -> codesurgeon.Struct
	16, // 3: codesurgeon.Package.functions:type_name -> codesurgeon.Function
	19, // 4: codesurgeon.Package.variables:type_name -> codesurgeon.Variable
	20, // 5: codesurgeon.Package.constants:type_name -> codesurgeon.Constant
	13, // 6: codesurgeon.Package.interfaces:type_name -> codesurgeon.Interface
	15, // 7: codesurgeon.Interface.methods:type_name -> codesurgeon.Method
	18, // 8: codesurgeon.Struct.fields:type_name -> codesurgeon.Field
	15, // 9: codesurgeon.Struct.methods:type_name -> codesurgeon.Method
	17, // 10: codesurgeon.Method.params:type_name -> codesurgeon.Param
	17, // 11: codesurgeon.Method.returns:type_name -> codesurgeon.Param
	17, // 12: codesurgeon.Function.params:type_name -> codesurgeon.Param
	17, // 13: codesurgeon.Function.returns:type_name -> codesurgeon.Param
	0,  // 14: codesurgeon.GptService.GetOpenAPI:input_type -> codesurgeon.GetOpenAPIRequest
	2,  // 15: codesurgeon.GptService.Introduction:input_type -> codesurgeon.IntroductionRequest
	10, // 16: codesurgeon.GptService.ParseCodebase:input_type -> codesurgeon.ParseCodebaseRequest
	4,  // 17: codesurgeon.GptService.SearchForFunction:input_type -> codesurgeon.SearchForFunctionRequest
	6,  // 18: codesurgeon.GptService.UpsertDocumentationToFunction:input_type -> codesurgeon.UpsertDocumentationToFunctionRequest
	8,  // 19: codesurgeon.GptService.UpsertCodeBlock:input_type -> codesurgeon.UpsertCodeBlockRequest
	1,  // 20: codesurgeon.GptService.GetOpenAPI:output_type -> codesurgeon.GetOpenAPIResponse
	3,  // 21: codesurgeon.GptService.Introduction:output_type -> codesurgeon.IntroductionResponse
	11, // 22: codesurgeon.GptService.ParseCodebase:output_type -> codesurgeon.ParseCodebaseResponse
	5,  // 23: codesurgeon.GptService.SearchForFunction:output_type -> codesurgeon.SearchForFunctionResponse
	7,  // 24: codesurgeon.GptService.UpsertDocumentationToFunction:output_type -> codesurgeon.UpsertDocumentationToFunctionResponse
	9,  // 25: codesurgeon.GptService.UpsertCodeBlock:output_type -> codesurgeon.UpsertCodeBlockResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_codesurgeon_proto_init() }
func file_api_codesurgeon_proto_init() {
	if File_api_codesurgeon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_codesurgeon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetOpenAPIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetOpenAPIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*IntroductionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IntroductionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SearchForFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SearchForFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertDocumentationToFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertDocumentationToFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertCodeBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertCodeBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ParseCodebaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ParseCodebaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Struct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Method); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*Variable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Constant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_codesurgeon_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertCodeBlockRequest_Modification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_codesurgeon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_codesurgeon_proto_goTypes,
		DependencyIndexes: file_api_codesurgeon_proto_depIdxs,
		MessageInfos:      file_api_codesurgeon_proto_msgTypes,
	}.Build()
	File_api_codesurgeon_proto = out.File
	file_api_codesurgeon_proto_rawDesc = nil
	file_api_codesurgeon_proto_goTypes = nil
	file_api_codesurgeon_proto_depIdxs = nil
}
